version: "3.9"
services:
  oracledb:
    hostname: oracledb
    container_name: oracledb
    image: w4bo/oracle11g-java:latest
    environment:
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ALLOW_REMOTE=true
    ports:
      - "${ORACLE_PORT}:1521"
    volumes:
      - ./resources/:/data
      - ./resources/oracle11g/:/docker-entrypoint-initdb.d/
